version: '3'
services:
  api:
    build: 
      context: .
      dockerfile: Dockerfile
    ports: 
      - "3000:3000"
    environment: 
      - SERVICE_NAME=matches-api 
      - LOG_LEVEL=DEBUG
      - NODE_ENV=development